### ISSUE TITLE
The bootstrap path in phpunit.xml must be relative

### ISSUE THREAD

**Issue by ruudk** [jwage/phpchunkit#15]
This is my (a part) of my phpunit.xml:
```xml
<phpunit bootstrap="app/phpunit_bootstrap.php">
```

When I run phpchunkit I get an error:
```
$ vendor/bin/phpchunkit functional --num-chunks=1
Total Tests: 82
Number of Chunks Configured: 1
Number of Chunks Produced: 1
Tests Per Chunk: ~82
-----------

Running chunk #1
 82/82 [============================] 100%
PHPUnit 5.5.5 by Sebastian Bergmann and contributors.

Cannot open file "/tmp/app/phpunit_bootstrap.php".
```

When I change my bootstrap to
```xml
<phpunit bootstrap="./app/phpunit_bootstrap.php">
```

it works.

Don't know if this is my bad configuration or that phpchunkit doesn't handle it well.

**Comment by jwage** [comment]
If you don't prefix it with ./ then I believe it will assume your current working directory.

**Comment by ruudk** [comment]
But for some reason it picks `/tmp` ? While I am in `/www/myProjectName`

**Comment by jwage** [comment]
Oh, I just realized this is in your phpunit.xml config, not phpchunkit.xml.
