### ISSUE TITLE
PSR-4

### ISSUE THREAD

**Issue by wiese** [jwage/phpchunkit#4]
Hi,

just a suggestion given the rename, though it's completely internal to the package and really no issue for users. Using PSR-4 instead of PSR-0 could make organizing the resources a tad easier.

Cheers

**Comment by jwage** [comment]
I think I probably already adhere to psr 4 right? What changes would need to be made?

**Comment by wiese** [comment]
You are right. The benefit would be losing the redundant "PHPChunkit" folders in src and tests, make the whole thing easier to browse. Forked off, but aside of the basic autoloading there is quite a bit of relative directories (../../) and reflection going on so I'll need a bit.
https://github.com/wiese/phpchunkit/tree/patch-4

**Comment by wiese** [comment]
I performed the required changes but discovered a problem. The project is not able to correctly test PSR-4 projects (would have come up then), not even itself now, as it assumes/reimplements PSR-0 logic in TestCounter.
https://github.com/jwage/phpchunkit/compare/master...wiese:patch-4?expand=1#diff-cda651cf3fcec041396ee49ebe514f6cR33

The leanest way to not reinvent the wheel would probably be to ask composer for help, building a classmap and pulling the required information out of that. But this is a major change. What do you think?

Thanks

**Comment by jwage** [comment]
@wiese That could work fine. I am ok with it depending on composer. You could also require_once the file first and maybe do a comparison of get_declared_classes() before and after?

**Comment by iltar** [comment]
If paths are an "issue": https://github.com/hostnet/path-composer-plugin-lib

**Comment by wiese** [comment]
Hi,

get_declared_classes() is not really an option, as the file could already be loaded. I think token analysis is indeed the cleanest way - the best part is that we don't need to implement it.
Please see #12 

Cheers

**Comment by wiese** [comment]
#12, which is now in the main line,
* restructures the project to follow PSR-4
* allows the project to run tests in other projects that do not follow PSR-0
* fixes an [Exception bug](https://github.com/jwage/phpchunkit/commit/b9e54265cb4dcc627f76c487b376593a7c4856d4#diff-d3e34925893e52260aed5c00975b6fcbL185)

Thanks, Jonathan, for your help.

Cheers
